/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atividademonitoria;

import java.util.ArrayList;
import com.mycompany.atividademonitoria.modelagem.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonia Ribeiro
 */
public class AtividadeMonitoria extends javax.swing.JFrame {

    /**
     * Creates new form AtividadeMonitoria
     */
    public AtividadeMonitoria() {
        initComponents();
        adicionarNoCodigo();
    }
    
    ArrayList<Obra> listaObras = new ArrayList<>();
    
    private void adicionarNoCodigo(){
        listaObras.add(new Artigo(1, "CEULP/ULBRA", "Uso de IA nas Escolas", "Edoardo", 2026));
        listaObras.add(new Livro(80, "Aventura", "The Witcher: Torre da Andorinha", "Andrew Sapkowsky", 1990));
        listaObras.add(new Revista(72, "Mensal", "Criação de Jogos", "Igor", 2026));
    }

    
    private Obra procurarObra(String titulo){
        for (var obra : listaObras){
            if (obra.getTitulo().equalsIgnoreCase(titulo)){
                return obra;
            }
        }
        JOptionPane.showMessageDialog(null, "Obra não encontrada!");
        return null;
    }
   
    private int procurarIndex(Obra obraI){
        var num = 0;
        for (var obra : listaObras){
            if (obra.getTitulo().equalsIgnoreCase(obraI.getTitulo())){
                return num;
            }
            num++;
        }
        return num;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_mostrar_acervo = new javax.swing.JButton();
        btn_criar_livro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gerência Biblioteca");

        btn_mostrar_acervo.setText("Mostrar Acervo");
        btn_mostrar_acervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_acervoActionPerformed(evt);
            }
        });

        btn_criar_livro.setText("Cadastrar Livro");
        btn_criar_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criar_livroActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar Revista");

        jButton3.setText("Cadastrar Artigo");

        jButton1.setText("Editar Obra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Apagar Obra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(btn_mostrar_acervo)
                            .addComponent(jButton1))
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(btn_criar_livro))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_criar_livro)
                    .addComponent(jButton4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btn_mostrar_acervo)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrar_acervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_acervoActionPerformed
        var retorno = "";
        for (var obra : listaObras){
            if (obra instanceof Artigo){
                retorno = retorno + "\nTipo: Artigo \n" + obra.exibirResumo();
            }
            else if (obra instanceof Livro){
                retorno = retorno + "\nTipo: Livro \n" + obra.exibirResumo();
            }
            else {
                try {
                    retorno = retorno + "\nTipo: Revista\n" + obra.exibirResumo();
                } catch (Exception e){
                    e.printStackTrace();
                    System.err.println("Obra é Nula: " + e.getMessage());
                }
            }            
        }
        JOptionPane.showMessageDialog(null, retorno);
    }//GEN-LAST:event_btn_mostrar_acervoActionPerformed

    private void btn_criar_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criar_livroActionPerformed
        
    }//GEN-LAST:event_btn_criar_livroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var tituloProc = JOptionPane.showInputDialog("Digite o título da obra: ");
        Obra obra = procurarObra(tituloProc);
        int index = procurarIndex(obra);
        if (obra != null){
            var novoTitulo = JOptionPane.showInputDialog("Digite o novo nome da obra: ");
            var novoAutor = JOptionPane.showInputDialog("Digite o novo autor: ");
            var novoData = Integer.parseInt(JOptionPane.showInputDialog("Digite a nova data: "));
            obra.setAutor(novoAutor);
            obra.setTitulo(novoTitulo);
            obra.setDataPub(novoData);
            listaObras.set(index, obra);
        }
        else {
            JOptionPane.showMessageDialog(null, "Obra inválida!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtividadeMonitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtividadeMonitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtividadeMonitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtividadeMonitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtividadeMonitoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_criar_livro;
    private javax.swing.JButton btn_mostrar_acervo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
