/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rh;
import com.mycompany.rh.funcionarios.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Antonia Ribeiro
 */
public class RH extends javax.swing.JFrame {

    ArrayList<Funcionario> listaFunc = new ArrayList<>();
    
    private int idAtual = 0;
    
    private int aumentarID(){
        idAtual++;
        return idAtual;
    }
    /**
     * Creates new form RH
     */
    public RH() {
        initComponents();
        inserirNoCodigo();
    }

    private void inserirNoCodigo(){
        listaFunc.add(new Designer(aumentarID(), "Edoardo", 2800, 190));
        listaFunc.add(new Gerente(aumentarID(), "Fulano", 5000));
        listaFunc.add(new Estagiario(aumentarID(), "Ciclano", 1600));
        listaFunc.add(new Desenvolvedor(4, listaFunc.get(1).getId(), aumentarID(), "Ana", 4500));
        
    }
    
    private double salarioBruto(){
        var salarioBruto = 0D;
        
        for (Funcionario func : listaFunc){
            salarioBruto += func.getSalarioBase();
        }
        
        return salarioBruto;
    }
    
    private double apenasBonus(){
        var bonus = 0D;
        
        for (Funcionario func : listaFunc){
            if (func instanceof Estagiario){
                bonus += 0;
            }
            else if (func instanceof Designer){
                bonus += ((Designer) func).getAdicional();
            }
            else if (func instanceof Desenvolvedor){
                bonus += ((Desenvolvedor) func).calcularBonus();
            }
            else if (func instanceof Gerente){
                for (Funcionario devs : listaFunc){
                    if (devs instanceof Desenvolvedor){
                        if (((Desenvolvedor) devs).getIdChefe() == acharFunc(func.getId()).getId()){
                            bonus += ((Desenvolvedor) devs).calcularBonus();
                        }
                    }
                }
            }
        }
        return bonus;
    }
    
    private void total(){
        
    }
    
    private double calcGerente(int id){
        Gerente gerente = new Gerente();
        double folha = 0;
        for (Funcionario func : listaFunc){
            if (func.getId() == id){
                if (func instanceof Gerente){
                    gerente = (Gerente) func;
                }
            }
        }
        
        for (Funcionario func : listaFunc){
            if (func instanceof Desenvolvedor){
                if (((Desenvolvedor) func).getIdChefe() == gerente.getId()){
                    folha += ((Desenvolvedor) func).calcularBonus();
                }
            }
        }
        
        return folha;
    }
   
    private Funcionario acharFunc(int id){
        for (Funcionario func : listaFunc){
            if (func.getId() == id){
                return func;
            }
        }
        return null;
    }
   
    private Funcionario acharFunc(String nome){
        for (Funcionario func : listaFunc){
            if (func.getNome().equalsIgnoreCase(nome)){
                return func;
            }
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_ID = new javax.swing.JRadioButton();
        btn_nome = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        radio_bonus = new javax.swing.JRadioButton();
        radio_bruto = new javax.swing.JRadioButton();
        radio_total = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Adicionar Funcionario");

        jButton2.setText("Mostrar Funcionários");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Procurar Funcionário");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_ID);
        btn_ID.setText("ID");
        btn_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IDActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_nome);
        btn_nome.setText("Nome");

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Gerente");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Designer");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Desenvolvedor");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Estagiário");

        jButton4.setText("Folha Salarial");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(radio_bonus);
        radio_bonus.setText("Apenas Bônus");

        buttonGroup3.add(radio_bruto);
        radio_bruto.setText("Bruto");

        buttonGroup3.add(radio_total);
        radio_total.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jButton1)
                            .addComponent(jRadioButton4))
                        .addGap(0, 558, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_ID)
                                .addComponent(jButton3)
                                .addComponent(btn_nome)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radio_bruto)
                                        .addComponent(radio_bonus)
                                        .addComponent(radio_total)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(radio_bonus))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(radio_bruto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(btn_ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_nome)
                .addGap(54, 54, 54)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        var sb = new StringBuilder();
        
        for (Funcionario func : listaFunc){
            sb.append(func.toString()).append("\n");
        }
        
        JOptionPane.showMessageDialog(null, sb.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_IDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (btn_nome.isSelected()){
            var nomeProcura = JOptionPane.showInputDialog("Digite o nome do funcionário");
            
            var func = acharFunc(nomeProcura);
            
            if (func != null){
               JOptionPane.showMessageDialog(null, func.toString());
            }
            else {
                 JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
            }
        }
        
        else if (btn_ID.isSelected()){
            var idProcura = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID: "));
            
            var func = acharFunc(idProcura);
            
            if (func != null){
                JOptionPane.showMessageDialog(null, func.toString());
            }
            else {
                JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione um dos métodos de procura!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (radio_bonus.isSelected()){
            JOptionPane.showMessageDialog(null, apenasBonus());
        }
        else if (radio_bruto.isSelected()){
            JOptionPane.showMessageDialog(null, salarioBruto());
        }
        else if (radio_total.isSelected()){
            JOptionPane.showMessageDialog(null, salarioBruto() + apenasBonus());
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione algum botão!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_ID;
    private javax.swing.JRadioButton btn_nome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton radio_bonus;
    private javax.swing.JRadioButton radio_bruto;
    private javax.swing.JRadioButton radio_total;
    // End of variables declaration//GEN-END:variables
}
